# DASHBOARDS-CLUSTER-1 values for node-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

chainName: kusama
nodeSelector: {}

cloudsql:
  commandline:
    args: "-instances=premiurly-284711:europe-west1:polkassembly=tcp:5432"

nodeWatcher:
  dbName: "kusama-chain-db"
  dbUser: "chain-db"
  dbPassword: from-gitlab-vars

harvester:
  config:
    ARCHIVE_NODE_ENDPOINT: wss://kusama.api.onfinality.io/public-ws
    START_FROM: '10418197'
    BLOCK_IDENTIFIER: chain-tip-10418197
